#!/usr/bin/env python3
"""
DetectForge PR Reporting Bot
Formats linting, conversion, and test harness execution results into a clean markdown comment
and posts/updates it on the pull request via GitHub REST API.
"""

import sys
import os
import json
import urllib.request
import urllib.parse
from pathlib import Path

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

def build_pr_comment_body(test_results_file: Path) -> str:
    comment = []
    comment.append("### 🔍 DetectForge CI Test Report\n")
    
    if not test_results_file.exists():
        comment.append("⚠️ **No test results found.**\n")
        return "\n".join(comment)

    try:
        with open(test_results_file, 'r', encoding='utf-8') as f:
            results = json.load(f)
    except Exception as e:
        comment.append(f"❌ Failed to parse test results: `{e}`\n")
        return "\n".join(comment)

    comment.append("| Rule Slug | True Positive Assertion | False Positive Assertion | Status |")
    comment.append("| :--- | :---: | :---: | :---: |")

    total_rules = len(results)
    passed_rules = 0

    for r in results:
        slug = r.get("slug", "unknown")
        tp_pass = r.get("tp_passed", 0)
        tp_fail = r.get("tp_failed", 0)
        fp_pass = r.get("fp_passed", 0)
        fp_fail = r.get("fp_failed", 0)
        
        tp_str = f"✅ {tp_pass} pass" if tp_fail == 0 else f"❌ {tp_fail} fail"
        fp_str = f"✅ {fp_pass} pass" if fp_fail == 0 else f"❌ {fp_fail} fail"
        
        if tp_fail == 0 and fp_fail == 0 and not r.get("errors"):
            status_str = "✅ **PASSED**"
            passed_rules += 1
        else:
            status_str = "❌ **FAILED**"
            
        comment.append(f"| `{slug}` | {tp_str} | {fp_str} | {status_str} |")

    comment.append(f"\n**Summary:** {passed_rules}/{total_rules} rule test suites passed.")
    comment.append("\n*Automated report generated by DetectForge CI Bot* 🤖")
    return "\n".join(comment)

def post_github_comment(body: str):
    token = os.environ.get("GITHUB_TOKEN")
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    
    if not token or not event_path:
        print("[*] GITHUB_TOKEN or GITHUB_EVENT_PATH not set. Skipping live PR comment post (local run mode).")
        print("\n--- PR Comment Preview ---")
        print(body)
        print("--------------------------")
        return

    try:
        with open(event_path, 'r', encoding='utf-8') as f:
            event = json.load(f)
            
        pr_number = event.get("number")
        repo = event.get("repository", {}).get("full_name")
        
        if not pr_number or not repo:
            print("[!] Event data missing PR number or repository full_name.")
            return

        url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "DetectForge-Bot"
        }
        
        data = json.dumps({"body": body}).encode('utf-8')
        req = urllib.request.Request(url, data=data, headers=headers, method="POST")
        
        with urllib.request.urlopen(req) as resp:
            if resp.status in (200, 201):
                print(f"[+] Successfully posted PR comment to #{pr_number}")
            else:
                print(f"[!] GitHub API returned status {resp.status}")
    except Exception as e:
        print(f"[!] Error posting PR comment: {e}", file=sys.stderr)

def main():
    test_results_path = Path("build/test_results.json")
    comment_body = build_pr_comment_body(test_results_path)
    post_github_comment(comment_body)

if __name__ == "__main__":
    main()
